#!/usr/bin/python
import os
import signal
import sys


def disable(activity):
    if os.path.islink(f"active/{activity}"):
        os.remove(f"active/{activity}")
    bump()


def bump():
    with open("/tmp/overseer.pid", 'r') as content_file:
        pid = content_file.read()
        pid = int(pid)
        os.kill(pid, signal.SIGUSR1)


if len(sys.argv) != 2:
    print("Must pass 1 argument!")
    exit(1)

disable(sys.argv[1])