#!/usr/bin/python
import os
from shutil import copyfile
import signal
import sys


def enable(activity):
    if not os.path.isfile(f"today/{activity}"):
        copyfile(f"plan/{activity}", f"today/{activity}")

    if not os.path.islink(f"active/{activity}"):
        os.symlink(f"today/{activity}", f"active/{activity}")

    bump()


def bump():
    with open("/tmp/overseer.pid", 'r') as content_file:
        pid = content_file.read()
        pid = int(pid)
        os.kill(pid, signal.SIGUSR1)

if len(sys.argv) != 2:
    print("Must pass 1 argument!")
    exit(1)

enable(sys.argv[1])
