#!/usr/bin/bash

pihole -w -nr 3gppnetwork.org
pihole -w -nr analytics.google.com
pihole -w -nr app-measurement.com
pihole -w -nr cdn.optimizely.com
pihole -w -nr csi.gstatic.com
pihole --wild -d -nr crashlytics.com
pihole --wild -d -nr doubleclick.net

pihole -w -nr e.crashlytics.com
pihole -w -nr crashlytics.com

pihole -w -nr www.analytics.google.com
pihole -w -nr www.google-analytics.com
pihole -w -nr www.googleadservices.com
pihole -w -nr www.googletagmanager.com

pihole restartdns
