#!/usr/bin/bash

ADDRESS='localhost:8086'
DB='overseer'
TIMESTAMP=$(date +%s)000000000

for activity in /etc/overseer/activities/*; do
	
	ACT_NAME=`basename $activity`
	ACT_NAME="${ACT_NAME%.*}"

	ACTIVE=0
	
	if [ -L "/etc/overseer/status/$ACT_NAME" ]
	then
		ACTIVE=1
	fi

	curl -i -XPOST "http://$ADDRESS/write?db=$DB" --data-binary "active,activity=$ACT_NAME value=$ACTIVE $TIMESTAMP"
done

for activity in /etc/overseer/timers/*; do
	TIMEUSED=$(cat $activity)
	ACT_NAME=`basename $activity`
	curl -i -XPOST "http://$ADDRESS/write?db=$DB" --data-binary "timeTracked,activity=$ACT_NAME value=$TIMEUSED $TIMESTAMP"
done

for activity in /etc/overseer/rev_timers/*; do
	TIMELEFT=$(cat $activity)
	ACT_NAME=`basename $activity`
	curl -i -XPOST "http://$ADDRESS/write?db=$DB" --data-binary "timeLeft,activity=$ACT_NAME value=$TIMELEFT $TIMESTAMP"
done
