#!/usr/bin/bash

pihole -b -nr 3gppnetwork.org
pihole -b -nr analytics.google.com
pihole -b -nr app-measurement.com
pihole -b -nr cdn.optimizely.com
pihole -b -nr csi.gstatic.com
pihole --wild -nr crashlytics.com
pihole --wild -nr doubleclick.net

pihole -b -nr crashlytics.com
pihole -b -nr e.crashlytics.com


pihole -b -nr www.analytics.google.com
pihole -b -nr www.google-analytics.com
pihole -b -nr www.googleadservices.com
pihole -b -nr www.googletagmanager.com

pihole restartdns
