#!/usr/bin/env bash

docker exec pihole pihole -w -nr youtube.com
docker exec pihole pihole -w -nr www.youtube.com
docker exec pihole pihole -w -nr youtubei.googleapis.com
docker exec pihole pihole --wild -d -nr googlevideo.com

docker exec pihole pihole restartdns
